AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  VpcIdParameter:
    Type: String
  KeyPairParameter:
    Type: String
  AmiIdParameter:
    Type: String

  InstanceTypeParameter:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t3.micro
      - t3.small
    Description: El tipo de instancia a crear

Outputs:
  PublicIp:
    Description: IP Publica de la instancia
    Value: !GetAtt WebServer.PublicIp
  PublicIp2:
    Description: IP Publica de la instancia
    Value:
      Fn::GetAtt: [ WebServer, PublicIp ]
  IdInstancia:
    Description: Id de la instancia que hemos creado
    Value:
      Ref: WebServer
  IdInstancia2:
    Description: Id de la instancia que hemos creado2
    Value: !Ref WebServer
  foo1:
    Description: foo
    Value: !Base64 hola mundo esto es una prueba
      

Description: >
  Este stack va a crear
  una instancia y todo 
  lo que necesita

Resources:
  WebServer:
    Type: 'AWS::EC2::Instance'
    Properties: 
      ImageId: 
        Ref: AmiIdParameter
      KeyName: 
        Ref: KeyPairParameter
      InstanceType: 
        Ref: InstanceTypeParameter
      SecurityGroupIds:
        - Ref: SecurityGroupSSH

  SecurityGroupSSH:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security Group que permite acceso SSH
      VpcId: 
        Ref: VpcIdParameter
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: -1
          FromPort: 0
          ToPort: 0
          CidrIp: 0.0.0.0/0

